### ISSUE TITLE
Page 12: Install the packages from the requirements.txt file:

### ISSUE THREAD

**Issue by andywenk** [nickjj/deploy-web-apps-with-docker#2]
Hi Nick,

first of all thanks for the book (purchased via leanpub). I am following the code and found a small problem. On page 12 you say 

```
Install the packages from the requirements.txt file:
pip install -r requirements.txt
```

As you mentioned before, one should be located in the directory `rediscounter`. That means the command should read:

```
pip install -r website/requirements.txt
```

All the best 

Andy

**Comment by nickjj** [comment]
Hi @andywenk,

Thanks a lot for investing in the book, I hope it serves you well.

You're right. I just fixed it and pushed a new version of the book. You can download it for free since you're entitled to free updates for life.

Also, I'm not sure when you purchased it but on September 12th I pushed out a version of the book that fixed about 20 grammar/typo mistakes along with a slight code adjustment in the later chapters. You might want to grab the latest copy if you downloaded it before then.

**Comment by andywenk** [comment]
Hi @nickjj,

cool ;-). I get a info when you release a new version and I download it immediately. So I am always up to date. But thanks for the info!

All the best

Andy
